# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systems/ajax/logging/proto/formatting_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='systems/ajax/logging/proto/formatting_options.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\032systems.ajax.logging.protoP\001\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3systems/ajax/logging/proto/formatting_options.proto\x1a google/protobuf/descriptor.proto:7\n\x0f\x64isable_logging\x12\x1d.google.protobuf.FieldOptions\x18\xcd\x08 \x01(\x08:2\n\nhash_value\x12\x1d.google.protobuf.FieldOptions\x18\xcf\x08 \x01(\x08\x42!\n\x1asystems.ajax.logging.protoP\x01\xba\x02\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


DISABLE_LOGGING_FIELD_NUMBER = 1101
disable_logging = _descriptor.FieldDescriptor(
  name='disable_logging', full_name='disable_logging', index=0,
  number=1101, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
HASH_VALUE_FIELD_NUMBER = 1103
hash_value = _descriptor.FieldDescriptor(
  name='hash_value', full_name='hash_value', index=1,
  number=1103, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['disable_logging'] = disable_logging
DESCRIPTOR.extensions_by_name['hash_value'] = hash_value
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(disable_logging)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(hash_value)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
