# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/hub/main/additional/data/firmware_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v1/hub/main/additional/data/firmware_info.proto',
  package='systems.ajax.a911.grpc.v1.hub.main.additional.data',
  syntax='proto3',
  serialized_options=b'\n2systems.ajax.a911.grpc.v1.hub.main.additional.dataP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/v1/hub/main/additional/data/firmware_info.proto\x12\x32systems.ajax.a911.grpc.v1.hub.main.additional.data\"\x7f\n\x0c\x46irmwareInfo\x12\x12\n\nfw_version\x18\x01 \x01(\t\x12\x19\n\x11\x64\x65vice_hw_version\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_band\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x65vice_type\x18\x04 \x01(\x05\x12\x16\n\x0e\x64\x65vice_subtype\x18\x05 \x01(\x05\x42\x36\n2systems.ajax.a911.grpc.v1.hub.main.additional.dataP\x01\x62\x06proto3'
)




_FIRMWAREINFO = _descriptor.Descriptor(
  name='FirmwareInfo',
  full_name='systems.ajax.a911.grpc.v1.hub.main.additional.data.FirmwareInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fw_version', full_name='systems.ajax.a911.grpc.v1.hub.main.additional.data.FirmwareInfo.fw_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_hw_version', full_name='systems.ajax.a911.grpc.v1.hub.main.additional.data.FirmwareInfo.device_hw_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_band', full_name='systems.ajax.a911.grpc.v1.hub.main.additional.data.FirmwareInfo.device_band', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='systems.ajax.a911.grpc.v1.hub.main.additional.data.FirmwareInfo.device_type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_subtype', full_name='systems.ajax.a911.grpc.v1.hub.main.additional.data.FirmwareInfo.device_subtype', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=230,
)

DESCRIPTOR.message_types_by_name['FirmwareInfo'] = _FIRMWAREINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirmwareInfo = _reflection.GeneratedProtocolMessageType('FirmwareInfo', (_message.Message,), {
  'DESCRIPTOR' : _FIRMWAREINFO,
  '__module__' : 'v1.hub.main.additional.data.firmware_info_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.a911.grpc.v1.hub.main.additional.data.FirmwareInfo)
  })
_sym_db.RegisterMessage(FirmwareInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
