# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/company/rapid-response-team.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.systems.ajax.logging.proto import formatting_options_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v1/company/rapid-response-team.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n!systems.ajax.a911.grpc.company.v1P\001\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$v1/company/rapid-response-team.proto\x1a\x33systems/ajax/logging/proto/formatting_options.proto\"\xb9\x03\n\x11RapidResponseTeam\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x64\x64ress_line\x18\x05 \x01(\t\x12-\n\x08location\x18\x06 \x01(\x0b\x32\x1b.RapidResponseTeam.Location\x12\x35\n\rphone_numbers\x18\x07 \x03(\x0b\x32\x1e.RapidResponseTeam.PhoneNumber\x12+\n\x07vehicle\x18\x08 \x01(\x0b\x32\x1a.RapidResponseTeam.Vehicle\x12\x0e\n\x06\x61\x63tive\x18\t \x01(\x08\x12\x0f\n\x07\x64\x65leted\x18\n \x01(\x08\x12\x0f\n\x07logo_id\x18\x0b \x01(\t\x1a\"\n\x0bPhoneNumber\x12\x13\n\x06number\x18\x01 \x01(\tB\x03\xf8\x44\x01\x1a/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x1a;\n\x07Vehicle\x12\x1b\n\x13registration_number\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"M\n\x1dLightWeightRapidResponseTeams\x12,\n\x05teams\x18\x01 \x03(\x0b\x32\x1d.LightWeightRapidResponseTeam\"W\n\x1cLightWeightRapidResponseTeam\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07logo_id\x18\x0b \x01(\tB(\n!systems.ajax.a911.grpc.company.v1P\x01\xba\x02\x00\x62\x06proto3'
  ,
  dependencies=[systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2.DESCRIPTOR,])




_RAPIDRESPONSETEAM_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='RapidResponseTeam.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='RapidResponseTeam.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\370D\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=425,
)

_RAPIDRESPONSETEAM_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='RapidResponseTeam.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='RapidResponseTeam.Location.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='RapidResponseTeam.Location.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=474,
)

_RAPIDRESPONSETEAM_VEHICLE = _descriptor.Descriptor(
  name='Vehicle',
  full_name='RapidResponseTeam.Vehicle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='registration_number', full_name='RapidResponseTeam.Vehicle.registration_number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='RapidResponseTeam.Vehicle.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=535,
)

_RAPIDRESPONSETEAM = _descriptor.Descriptor(
  name='RapidResponseTeam',
  full_name='RapidResponseTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RapidResponseTeam.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='RapidResponseTeam.version', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='RapidResponseTeam.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='RapidResponseTeam.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address_line', full_name='RapidResponseTeam.address_line', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='RapidResponseTeam.location', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone_numbers', full_name='RapidResponseTeam.phone_numbers', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='RapidResponseTeam.vehicle', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='RapidResponseTeam.active', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted', full_name='RapidResponseTeam.deleted', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logo_id', full_name='RapidResponseTeam.logo_id', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RAPIDRESPONSETEAM_PHONENUMBER, _RAPIDRESPONSETEAM_LOCATION, _RAPIDRESPONSETEAM_VEHICLE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=535,
)


_LIGHTWEIGHTRAPIDRESPONSETEAMS = _descriptor.Descriptor(
  name='LightWeightRapidResponseTeams',
  full_name='LightWeightRapidResponseTeams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='teams', full_name='LightWeightRapidResponseTeams.teams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=614,
)


_LIGHTWEIGHTRAPIDRESPONSETEAM = _descriptor.Descriptor(
  name='LightWeightRapidResponseTeam',
  full_name='LightWeightRapidResponseTeam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='LightWeightRapidResponseTeam.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='LightWeightRapidResponseTeam.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='LightWeightRapidResponseTeam.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logo_id', full_name='LightWeightRapidResponseTeam.logo_id', index=3,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=703,
)

_RAPIDRESPONSETEAM_PHONENUMBER.containing_type = _RAPIDRESPONSETEAM
_RAPIDRESPONSETEAM_LOCATION.containing_type = _RAPIDRESPONSETEAM
_RAPIDRESPONSETEAM_VEHICLE.containing_type = _RAPIDRESPONSETEAM
_RAPIDRESPONSETEAM.fields_by_name['location'].message_type = _RAPIDRESPONSETEAM_LOCATION
_RAPIDRESPONSETEAM.fields_by_name['phone_numbers'].message_type = _RAPIDRESPONSETEAM_PHONENUMBER
_RAPIDRESPONSETEAM.fields_by_name['vehicle'].message_type = _RAPIDRESPONSETEAM_VEHICLE
_LIGHTWEIGHTRAPIDRESPONSETEAMS.fields_by_name['teams'].message_type = _LIGHTWEIGHTRAPIDRESPONSETEAM
DESCRIPTOR.message_types_by_name['RapidResponseTeam'] = _RAPIDRESPONSETEAM
DESCRIPTOR.message_types_by_name['LightWeightRapidResponseTeams'] = _LIGHTWEIGHTRAPIDRESPONSETEAMS
DESCRIPTOR.message_types_by_name['LightWeightRapidResponseTeam'] = _LIGHTWEIGHTRAPIDRESPONSETEAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RapidResponseTeam = _reflection.GeneratedProtocolMessageType('RapidResponseTeam', (_message.Message,), {

  'PhoneNumber' : _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), {
    'DESCRIPTOR' : _RAPIDRESPONSETEAM_PHONENUMBER,
    '__module__' : 'v1.company.rapid_response_team_pb2'
    # @@protoc_insertion_point(class_scope:RapidResponseTeam.PhoneNumber)
    })
  ,

  'Location' : _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
    'DESCRIPTOR' : _RAPIDRESPONSETEAM_LOCATION,
    '__module__' : 'v1.company.rapid_response_team_pb2'
    # @@protoc_insertion_point(class_scope:RapidResponseTeam.Location)
    })
  ,

  'Vehicle' : _reflection.GeneratedProtocolMessageType('Vehicle', (_message.Message,), {
    'DESCRIPTOR' : _RAPIDRESPONSETEAM_VEHICLE,
    '__module__' : 'v1.company.rapid_response_team_pb2'
    # @@protoc_insertion_point(class_scope:RapidResponseTeam.Vehicle)
    })
  ,
  'DESCRIPTOR' : _RAPIDRESPONSETEAM,
  '__module__' : 'v1.company.rapid_response_team_pb2'
  # @@protoc_insertion_point(class_scope:RapidResponseTeam)
  })
_sym_db.RegisterMessage(RapidResponseTeam)
_sym_db.RegisterMessage(RapidResponseTeam.PhoneNumber)
_sym_db.RegisterMessage(RapidResponseTeam.Location)
_sym_db.RegisterMessage(RapidResponseTeam.Vehicle)

LightWeightRapidResponseTeams = _reflection.GeneratedProtocolMessageType('LightWeightRapidResponseTeams', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTWEIGHTRAPIDRESPONSETEAMS,
  '__module__' : 'v1.company.rapid_response_team_pb2'
  # @@protoc_insertion_point(class_scope:LightWeightRapidResponseTeams)
  })
_sym_db.RegisterMessage(LightWeightRapidResponseTeams)

LightWeightRapidResponseTeam = _reflection.GeneratedProtocolMessageType('LightWeightRapidResponseTeam', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTWEIGHTRAPIDRESPONSETEAM,
  '__module__' : 'v1.company.rapid_response_team_pb2'
  # @@protoc_insertion_point(class_scope:LightWeightRapidResponseTeam)
  })
_sym_db.RegisterMessage(LightWeightRapidResponseTeam)


DESCRIPTOR._options = None
_RAPIDRESPONSETEAM_PHONENUMBER.fields_by_name['number']._options = None
# @@protoc_insertion_point(module_scope)
