# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/facility/facility-maintenance.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v1/facility/facility-maintenance.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\"systems.ajax.a911.grpc.facility.v1P\001\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&v1/facility/facility-maintenance.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x01\n\x17\x46\x61\x63ilityMaintenanceData\x12\x13\n\x0b\x66\x61\x63ility_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63onnected_by\x18\x02 \x01(\t\x12\x14\n\x0cinstalled_by\x18\x03 \x01(\t\x12\x19\n\x11\x66\x61\x63ility_engineer\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x64 \x01(\x04\x12\x36\n\x12last_modified_date\x18\x65 \x01(\x0b\x32\x1a.google.protobuf.TimestampB)\n\"systems.ajax.a911.grpc.facility.v1P\x01\xba\x02\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_FACILITYMAINTENANCEDATA = _descriptor.Descriptor(
  name='FacilityMaintenanceData',
  full_name='FacilityMaintenanceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='facility_id', full_name='FacilityMaintenanceData.facility_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected_by', full_name='FacilityMaintenanceData.connected_by', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='installed_by', full_name='FacilityMaintenanceData.installed_by', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='facility_engineer', full_name='FacilityMaintenanceData.facility_engineer', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='FacilityMaintenanceData.version', index=4,
      number=100, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_modified_date', full_name='FacilityMaintenanceData.last_modified_date', index=5,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=266,
)

_FACILITYMAINTENANCEDATA.fields_by_name['last_modified_date'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['FacilityMaintenanceData'] = _FACILITYMAINTENANCEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FacilityMaintenanceData = _reflection.GeneratedProtocolMessageType('FacilityMaintenanceData', (_message.Message,), {
  'DESCRIPTOR' : _FACILITYMAINTENANCEDATA,
  '__module__' : 'v1.facility.facility_maintenance_pb2'
  # @@protoc_insertion_point(class_scope:FacilityMaintenanceData)
  })
_sym_db.RegisterMessage(FacilityMaintenanceData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
