# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/facility/facility-notes-endpoints.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.facility import facility_notes_pb2 as v1_dot_facility_dot_facility__notes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v1/facility/facility-notes-endpoints.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\"systems.ajax.a911.grpc.facility.v1\210\001\001\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*v1/facility/facility-notes-endpoints.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a v1/facility/facility-notes.proto\".\n\x17GetFacilityNotesRequest\x12\x13\n\x0b\x66\x61\x63ility_id\x18\x01 \x01(\t\"<\n\x19\x44\x65leteFacilityNoteRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x66\x61\x63ility_id\x18\x02 \x01(\t\"X\n\x1bReindexFacilityNotesRequest\x12\x13\n\x0b\x66\x61\x63ility_id\x18\x01 \x01(\t\x12\x12\n\nfrom_index\x18\x02 \x01(\r\x12\x10\n\x08to_index\x18\x03 \x01(\r2\xd8\x02\n\x14\x46\x61\x63ilityNotesService\x12@\n\x13streamFacilityNotes\x12\x18.GetFacilityNotesRequest\x1a\r.FacilityNote0\x01\x12\x32\n\x12\x63reateFacilityNote\x12\r.FacilityNote\x1a\r.FacilityNote\x12\x32\n\x12updateFacilityNote\x12\r.FacilityNote\x1a\r.FacilityNote\x12H\n\x12\x64\x65leteFacilityNote\x12\x1a.DeleteFacilityNoteRequest\x1a\x16.google.protobuf.Empty\x12L\n\x14reindexFacilityNotes\x12\x1c.ReindexFacilityNotesRequest\x1a\x16.google.protobuf.EmptyB*\n\"systems.ajax.a911.grpc.facility.v1\x88\x01\x01\xba\x02\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,v1_dot_facility_dot_facility__notes__pb2.DESCRIPTOR,])




_GETFACILITYNOTESREQUEST = _descriptor.Descriptor(
  name='GetFacilityNotesRequest',
  full_name='GetFacilityNotesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='facility_id', full_name='GetFacilityNotesRequest.facility_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=155,
)


_DELETEFACILITYNOTEREQUEST = _descriptor.Descriptor(
  name='DeleteFacilityNoteRequest',
  full_name='DeleteFacilityNoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeleteFacilityNoteRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='facility_id', full_name='DeleteFacilityNoteRequest.facility_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=217,
)


_REINDEXFACILITYNOTESREQUEST = _descriptor.Descriptor(
  name='ReindexFacilityNotesRequest',
  full_name='ReindexFacilityNotesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='facility_id', full_name='ReindexFacilityNotesRequest.facility_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_index', full_name='ReindexFacilityNotesRequest.from_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_index', full_name='ReindexFacilityNotesRequest.to_index', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=307,
)

DESCRIPTOR.message_types_by_name['GetFacilityNotesRequest'] = _GETFACILITYNOTESREQUEST
DESCRIPTOR.message_types_by_name['DeleteFacilityNoteRequest'] = _DELETEFACILITYNOTEREQUEST
DESCRIPTOR.message_types_by_name['ReindexFacilityNotesRequest'] = _REINDEXFACILITYNOTESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFacilityNotesRequest = _reflection.GeneratedProtocolMessageType('GetFacilityNotesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFACILITYNOTESREQUEST,
  '__module__' : 'v1.facility.facility_notes_endpoints_pb2'
  # @@protoc_insertion_point(class_scope:GetFacilityNotesRequest)
  })
_sym_db.RegisterMessage(GetFacilityNotesRequest)

DeleteFacilityNoteRequest = _reflection.GeneratedProtocolMessageType('DeleteFacilityNoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFACILITYNOTEREQUEST,
  '__module__' : 'v1.facility.facility_notes_endpoints_pb2'
  # @@protoc_insertion_point(class_scope:DeleteFacilityNoteRequest)
  })
_sym_db.RegisterMessage(DeleteFacilityNoteRequest)

ReindexFacilityNotesRequest = _reflection.GeneratedProtocolMessageType('ReindexFacilityNotesRequest', (_message.Message,), {
  'DESCRIPTOR' : _REINDEXFACILITYNOTESREQUEST,
  '__module__' : 'v1.facility.facility_notes_endpoints_pb2'
  # @@protoc_insertion_point(class_scope:ReindexFacilityNotesRequest)
  })
_sym_db.RegisterMessage(ReindexFacilityNotesRequest)


DESCRIPTOR._options = None

_FACILITYNOTESSERVICE = _descriptor.ServiceDescriptor(
  name='FacilityNotesService',
  full_name='FacilityNotesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=310,
  serialized_end=654,
  methods=[
  _descriptor.MethodDescriptor(
    name='streamFacilityNotes',
    full_name='FacilityNotesService.streamFacilityNotes',
    index=0,
    containing_service=None,
    input_type=_GETFACILITYNOTESREQUEST,
    output_type=v1_dot_facility_dot_facility__notes__pb2._FACILITYNOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='createFacilityNote',
    full_name='FacilityNotesService.createFacilityNote',
    index=1,
    containing_service=None,
    input_type=v1_dot_facility_dot_facility__notes__pb2._FACILITYNOTE,
    output_type=v1_dot_facility_dot_facility__notes__pb2._FACILITYNOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateFacilityNote',
    full_name='FacilityNotesService.updateFacilityNote',
    index=2,
    containing_service=None,
    input_type=v1_dot_facility_dot_facility__notes__pb2._FACILITYNOTE,
    output_type=v1_dot_facility_dot_facility__notes__pb2._FACILITYNOTE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteFacilityNote',
    full_name='FacilityNotesService.deleteFacilityNote',
    index=3,
    containing_service=None,
    input_type=_DELETEFACILITYNOTEREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='reindexFacilityNotes',
    full_name='FacilityNotesService.reindexFacilityNotes',
    index=4,
    containing_service=None,
    input_type=_REINDEXFACILITYNOTESREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACILITYNOTESSERVICE)

DESCRIPTOR.services_by_name['FacilityNotesService'] = _FACILITYNOTESSERVICE

# @@protoc_insertion_point(module_scope)
