# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/common/video/videoedge/archive/calendar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2/common/video/videoedge/archive/calendar.proto',
  package='systems.ajax.api.desktop.v2.common.video.videoedge.archive',
  syntax='proto3',
  serialized_options=b'P\001\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0v2/common/video/videoedge/archive/calendar.proto\x12:systems.ajax.api.desktop.v2.common.video.videoedge.archive\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x01\n\x08\x43\x61lendar\x12-\n\tstart_day\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\x0c\x12\\\n\x06tz_map\x18\x03 \x03(\x0b\x32L.systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.TzEntry\x1a\x43\n\x07TzEntry\x12\'\n\x03\x64\x61y\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07offsets\x18\x02 \x03(\x05\x42\x05P\x01\xba\x02\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CALENDAR_TZENTRY = _descriptor.Descriptor(
  name='TzEntry',
  full_name='systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.TzEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.TzEntry.day', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offsets', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.TzEntry.offsets', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=380,
)

_CALENDAR = _descriptor.Descriptor(
  name='Calendar',
  full_name='systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_day', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.start_day', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='days', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.days', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tz_map', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.tz_map', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CALENDAR_TZENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=380,
)

_CALENDAR_TZENTRY.fields_by_name['day'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CALENDAR_TZENTRY.containing_type = _CALENDAR
_CALENDAR.fields_by_name['start_day'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CALENDAR.fields_by_name['tz_map'].message_type = _CALENDAR_TZENTRY
DESCRIPTOR.message_types_by_name['Calendar'] = _CALENDAR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Calendar = _reflection.GeneratedProtocolMessageType('Calendar', (_message.Message,), {

  'TzEntry' : _reflection.GeneratedProtocolMessageType('TzEntry', (_message.Message,), {
    'DESCRIPTOR' : _CALENDAR_TZENTRY,
    '__module__' : 'v2.common.video.videoedge.archive.calendar_pb2'
    # @@protoc_insertion_point(class_scope:systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar.TzEntry)
    })
  ,
  'DESCRIPTOR' : _CALENDAR,
  '__module__' : 'v2.common.video.videoedge.archive.calendar_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.api.desktop.v2.common.video.videoedge.archive.Calendar)
  })
_sym_db.RegisterMessage(Calendar)
_sym_db.RegisterMessage(Calendar.TzEntry)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
