# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/common/video/videoedge/network/network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2/common/video/videoedge/network/network.proto',
  package='systems.ajax.api.desktop.v2.common.video.videoedge.network',
  syntax='proto3',
  serialized_options=b'P\001\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/v2/common/video/videoedge/network/network.proto\x12:systems.ajax.api.desktop.v2.common.video.videoedge.network\x1a\x1egoogle/protobuf/duration.proto\"\xb9\x03\n\x07Network\x12\x37\n\x14server_ping_interval\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x41\n\x1e\x63onnection_failure_alarm_delay\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12_\n\x08\x65thernet\x18\x03 \x01(\x0b\x32M.systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkTechnology\x12[\n\x04wifi\x18\x04 \x01(\x0b\x32M.systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkTechnology\x12t\n\x14\x63onfiguration_status\x18\x64 \x01(\x0b\x32V.systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkConfigurationStatus\"&\n\x11NetworkTechnology\x12\x11\n\tsupported\x18\x01 \x01(\x08\"\xc4\x01\n\x1aNetworkConfigurationStatus\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12k\n\x05state\x18\x02 \x01(\x0e\x32\\.systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkConfigurationStatus.State\"%\n\x05State\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02OK\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x42\x05P\x01\xba\x02\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])



_NETWORKCONFIGURATIONSTATUS_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkConfigurationStatus.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=787,
  serialized_end=824,
)
_sym_db.RegisterEnumDescriptor(_NETWORKCONFIGURATIONSTATUS_STATE)


_NETWORK = _descriptor.Descriptor(
  name='Network',
  full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_ping_interval', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.Network.server_ping_interval', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connection_failure_alarm_delay', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.Network.connection_failure_alarm_delay', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ethernet', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.Network.ethernet', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wifi', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.Network.wifi', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='configuration_status', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.Network.configuration_status', index=4,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=585,
)


_NETWORKTECHNOLOGY = _descriptor.Descriptor(
  name='NetworkTechnology',
  full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkTechnology',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='supported', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkTechnology.supported', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=625,
)


_NETWORKCONFIGURATIONSTATUS = _descriptor.Descriptor(
  name='NetworkConfigurationStatus',
  full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkConfigurationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkConfigurationStatus.request_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkConfigurationStatus.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NETWORKCONFIGURATIONSTATUS_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=824,
)

_NETWORK.fields_by_name['server_ping_interval'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_NETWORK.fields_by_name['connection_failure_alarm_delay'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_NETWORK.fields_by_name['ethernet'].message_type = _NETWORKTECHNOLOGY
_NETWORK.fields_by_name['wifi'].message_type = _NETWORKTECHNOLOGY
_NETWORK.fields_by_name['configuration_status'].message_type = _NETWORKCONFIGURATIONSTATUS
_NETWORKCONFIGURATIONSTATUS.fields_by_name['state'].enum_type = _NETWORKCONFIGURATIONSTATUS_STATE
_NETWORKCONFIGURATIONSTATUS_STATE.containing_type = _NETWORKCONFIGURATIONSTATUS
DESCRIPTOR.message_types_by_name['Network'] = _NETWORK
DESCRIPTOR.message_types_by_name['NetworkTechnology'] = _NETWORKTECHNOLOGY
DESCRIPTOR.message_types_by_name['NetworkConfigurationStatus'] = _NETWORKCONFIGURATIONSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Network = _reflection.GeneratedProtocolMessageType('Network', (_message.Message,), {
  'DESCRIPTOR' : _NETWORK,
  '__module__' : 'v2.common.video.videoedge.network.network_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.api.desktop.v2.common.video.videoedge.network.Network)
  })
_sym_db.RegisterMessage(Network)

NetworkTechnology = _reflection.GeneratedProtocolMessageType('NetworkTechnology', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKTECHNOLOGY,
  '__module__' : 'v2.common.video.videoedge.network.network_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkTechnology)
  })
_sym_db.RegisterMessage(NetworkTechnology)

NetworkConfigurationStatus = _reflection.GeneratedProtocolMessageType('NetworkConfigurationStatus', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKCONFIGURATIONSTATUS,
  '__module__' : 'v2.common.video.videoedge.network.network_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.api.desktop.v2.common.video.videoedge.network.NetworkConfigurationStatus)
  })
_sym_db.RegisterMessage(NetworkConfigurationStatus)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
