# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/common/video/privacy/video_edge_permissions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common.video.privacy import channel_permissions_pb2 as v2_dot_common_dot_video_dot_privacy_dot_channel__permissions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2/common/video/privacy/video_edge_permissions.proto',
  package='systems.ajax.api.desktop.v2.common.video.privacy',
  syntax='proto3',
  serialized_options=b'\n0systems.ajax.api.desktop.v2.common.video.privacyP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n4v2/common/video/privacy/video_edge_permissions.proto\x12\x30systems.ajax.api.desktop.v2.common.video.privacy\x1a\x31v2/common/video/privacy/channel_permissions.proto\"\x92\x01\n\x14VideoEdgePermissions\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x61\n\x13\x63hannel_permissions\x18\x03 \x03(\x0b\x32\x44.systems.ajax.api.desktop.v2.common.video.privacy.ChannelPermissionsJ\x04\x08\x02\x10\x03\x42\x34\n0systems.ajax.api.desktop.v2.common.video.privacyP\x01\x62\x06proto3'
  ,
  dependencies=[v2_dot_common_dot_video_dot_privacy_dot_channel__permissions__pb2.DESCRIPTOR,])




_VIDEOEDGEPERMISSIONS = _descriptor.Descriptor(
  name='VideoEdgePermissions',
  full_name='systems.ajax.api.desktop.v2.common.video.privacy.VideoEdgePermissions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='systems.ajax.api.desktop.v2.common.video.privacy.VideoEdgePermissions.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_permissions', full_name='systems.ajax.api.desktop.v2.common.video.privacy.VideoEdgePermissions.channel_permissions', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=304,
)

_VIDEOEDGEPERMISSIONS.fields_by_name['channel_permissions'].message_type = v2_dot_common_dot_video_dot_privacy_dot_channel__permissions__pb2._CHANNELPERMISSIONS
DESCRIPTOR.message_types_by_name['VideoEdgePermissions'] = _VIDEOEDGEPERMISSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoEdgePermissions = _reflection.GeneratedProtocolMessageType('VideoEdgePermissions', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOEDGEPERMISSIONS,
  '__module__' : 'v2.common.video.privacy.video_edge_permissions_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.api.desktop.v2.common.video.privacy.VideoEdgePermissions)
  })
_sym_db.RegisterMessage(VideoEdgePermissions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
