# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/hub/main/device/motion_protect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.hub.main.device import common_device_pb2 as v1_dot_hub_dot_main_dot_device_dot_common__device__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v1/hub/main/device/motion_protect.proto',
  package='systems.ajax.a911.grpc.v1.hub.main',
  syntax='proto3',
  serialized_options=b'\n%systems.ajax.a911.grpc.v1.main.deviceP\001\272\002\007Systems',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'v1/hub/main/device/motion_protect.proto\x12\"systems.ajax.a911.grpc.v1.hub.main\x1a&v1/hub/main/device/common_device.proto\"\xa6\x04\n\rMotionProtect\x12J\n\x0b\x63ommon_part\x18\xe8\x07 \x01(\x0b\x32\x34.systems.ajax.a911.grpc.v1.hub.main.CommonDevicePart\x12V\n\x0esiren_triggers\x18. \x03(\x0e\x32>.systems.ajax.a911.grpc.v1.hub.main.MotionProtect.SirenTrigger\x12\x13\n\x0bsensitivity\x18\x32 \x01(\x05\x12\x15\n\ralways_active\x18\x33 \x01(\x08\x12K\n\x07subtype\x18\xc3\x01 \x01(\x0e\x32\x39.systems.ajax.a911.grpc.v1.hub.main.MotionProtect.Subtype\x12]\n\x10motion_protect_s\x18\x80\n \x01(\x0b\x32@.systems.ajax.a911.grpc.v1.hub.main.MotionProtect.MotionProtectSH\x00\x1a%\n\x0eMotionProtectS\x12\x13\n\x0b\x66\x61st_tamper\x18q \x01(\x08\"5\n\x0cSirenTrigger\x12\x19\n\x15NO_SIREN_TRIGGER_INFO\x10\x00\x12\n\n\x06MOTION\x10\x01\"/\n\x07Subtype\x12\x0e\n\nNO_SUBTYPE\x10\x00\x12\x14\n\x10MOTION_PROTECT_S\x10\x01\x42\n\n\x08subtypesB3\n%systems.ajax.a911.grpc.v1.main.deviceP\x01\xba\x02\x07Systemsb\x06proto3'
  ,
  dependencies=[v1_dot_hub_dot_main_dot_device_dot_common__device__pb2.DESCRIPTOR,])



_MOTIONPROTECT_SIRENTRIGGER = _descriptor.EnumDescriptor(
  name='SirenTrigger',
  full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.SirenTrigger',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_SIREN_TRIGGER_INFO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTION', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=556,
  serialized_end=609,
)
_sym_db.RegisterEnumDescriptor(_MOTIONPROTECT_SIRENTRIGGER)

_MOTIONPROTECT_SUBTYPE = _descriptor.EnumDescriptor(
  name='Subtype',
  full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.Subtype',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_SUBTYPE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTION_PROTECT_S', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=611,
  serialized_end=658,
)
_sym_db.RegisterEnumDescriptor(_MOTIONPROTECT_SUBTYPE)


_MOTIONPROTECT_MOTIONPROTECTS = _descriptor.Descriptor(
  name='MotionProtectS',
  full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.MotionProtectS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fast_tamper', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.MotionProtectS.fast_tamper', index=0,
      number=113, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=554,
)

_MOTIONPROTECT = _descriptor.Descriptor(
  name='MotionProtect',
  full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_part', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.common_part', index=0,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='siren_triggers', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.siren_triggers', index=1,
      number=46, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensitivity', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.sensitivity', index=2,
      number=50, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='always_active', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.always_active', index=3,
      number=51, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subtype', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.subtype', index=4,
      number=195, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_protect_s', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.motion_protect_s', index=5,
      number=1280, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MOTIONPROTECT_MOTIONPROTECTS, ],
  enum_types=[
    _MOTIONPROTECT_SIRENTRIGGER,
    _MOTIONPROTECT_SUBTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='subtypes', full_name='systems.ajax.a911.grpc.v1.hub.main.MotionProtect.subtypes',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=120,
  serialized_end=670,
)

_MOTIONPROTECT_MOTIONPROTECTS.containing_type = _MOTIONPROTECT
_MOTIONPROTECT.fields_by_name['common_part'].message_type = v1_dot_hub_dot_main_dot_device_dot_common__device__pb2._COMMONDEVICEPART
_MOTIONPROTECT.fields_by_name['siren_triggers'].enum_type = _MOTIONPROTECT_SIRENTRIGGER
_MOTIONPROTECT.fields_by_name['subtype'].enum_type = _MOTIONPROTECT_SUBTYPE
_MOTIONPROTECT.fields_by_name['motion_protect_s'].message_type = _MOTIONPROTECT_MOTIONPROTECTS
_MOTIONPROTECT_SIRENTRIGGER.containing_type = _MOTIONPROTECT
_MOTIONPROTECT_SUBTYPE.containing_type = _MOTIONPROTECT
_MOTIONPROTECT.oneofs_by_name['subtypes'].fields.append(
  _MOTIONPROTECT.fields_by_name['motion_protect_s'])
_MOTIONPROTECT.fields_by_name['motion_protect_s'].containing_oneof = _MOTIONPROTECT.oneofs_by_name['subtypes']
DESCRIPTOR.message_types_by_name['MotionProtect'] = _MOTIONPROTECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotionProtect = _reflection.GeneratedProtocolMessageType('MotionProtect', (_message.Message,), {

  'MotionProtectS' : _reflection.GeneratedProtocolMessageType('MotionProtectS', (_message.Message,), {
    'DESCRIPTOR' : _MOTIONPROTECT_MOTIONPROTECTS,
    '__module__' : 'v1.hub.main.device.motion_protect_pb2'
    # @@protoc_insertion_point(class_scope:systems.ajax.a911.grpc.v1.hub.main.MotionProtect.MotionProtectS)
    })
  ,
  'DESCRIPTOR' : _MOTIONPROTECT,
  '__module__' : 'v1.hub.main.device.motion_protect_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.a911.grpc.v1.hub.main.MotionProtect)
  })
_sym_db.RegisterMessage(MotionProtect)
_sym_db.RegisterMessage(MotionProtect.MotionProtectS)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
