# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/common/privacy/photo-on-demand-devices.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v1/common/privacy/photo-on-demand-devices.proto',
  package='systems.ajax.a911.grpc.v1.common.privacy',
  syntax='proto3',
  serialized_options=b'\n(systems.ajax.a911.grpc.v1.common.privacy\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/v1/common/privacy/photo-on-demand-devices.proto\x12(systems.ajax.a911.grpc.v1.common.privacy\"f\n\x14PhotoOnDemandDevices\x12N\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32=.systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevice\"\xb5\x03\n\x13PhotoOnDemandDevice\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12]\n\x0b\x64\x65vice_type\x18\x02 \x01(\x0e\x32H.systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevice.DeviceType\"\xab\x02\n\nDeviceType\x12\x1b\n\x17\x44\x45VICE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x44\x45VICE_TYPE_MOTION_CAM\x10\x01\x12\"\n\x1e\x44\x45VICE_TYPE_MOTION_CAM_OUTDOOR\x10\x02\x12\x1f\n\x1b\x44\x45VICE_TYPE_MOTION_CAM_PHOD\x10\x03\x12\'\n#DEVICE_TYPE_MOTION_CAM_OUTDOOR_PHOD\x10\x04\x12%\n!DEVICE_TYPE_MOTION_CAM_PHOD_FIBRA\x10\x05\x12\x30\n,DEVICE_TYPE_MOTION_CAM_OUTDOOR_TWO_FOUR_PHOD\x10\x06\x12\x1d\n\x19\x44\x45VICE_TYPE_MOTION_CAM_HD\x10\x07\x42-\n(systems.ajax.a911.grpc.v1.common.privacy\xba\x02\x00\x62\x06proto3'
)



_PHOTOONDEMANDDEVICE_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevice.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MOTION_CAM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MOTION_CAM_OUTDOOR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MOTION_CAM_PHOD', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MOTION_CAM_OUTDOOR_PHOD', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MOTION_CAM_PHOD_FIBRA', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MOTION_CAM_OUTDOOR_TWO_FOUR_PHOD', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_TYPE_MOTION_CAM_HD', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=336,
  serialized_end=635,
)
_sym_db.RegisterEnumDescriptor(_PHOTOONDEMANDDEVICE_DEVICETYPE)


_PHOTOONDEMANDDEVICES = _descriptor.Descriptor(
  name='PhotoOnDemandDevices',
  full_name='systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevices.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=195,
)


_PHOTOONDEMANDDEVICE = _descriptor.Descriptor(
  name='PhotoOnDemandDevice',
  full_name='systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevice.device_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevice.device_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PHOTOONDEMANDDEVICE_DEVICETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=635,
)

_PHOTOONDEMANDDEVICES.fields_by_name['devices'].message_type = _PHOTOONDEMANDDEVICE
_PHOTOONDEMANDDEVICE.fields_by_name['device_type'].enum_type = _PHOTOONDEMANDDEVICE_DEVICETYPE
_PHOTOONDEMANDDEVICE_DEVICETYPE.containing_type = _PHOTOONDEMANDDEVICE
DESCRIPTOR.message_types_by_name['PhotoOnDemandDevices'] = _PHOTOONDEMANDDEVICES
DESCRIPTOR.message_types_by_name['PhotoOnDemandDevice'] = _PHOTOONDEMANDDEVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhotoOnDemandDevices = _reflection.GeneratedProtocolMessageType('PhotoOnDemandDevices', (_message.Message,), {
  'DESCRIPTOR' : _PHOTOONDEMANDDEVICES,
  '__module__' : 'v1.common.privacy.photo_on_demand_devices_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevices)
  })
_sym_db.RegisterMessage(PhotoOnDemandDevices)

PhotoOnDemandDevice = _reflection.GeneratedProtocolMessageType('PhotoOnDemandDevice', (_message.Message,), {
  'DESCRIPTOR' : _PHOTOONDEMANDDEVICE,
  '__module__' : 'v1.common.privacy.photo_on_demand_devices_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.a911.grpc.v1.common.privacy.PhotoOnDemandDevice)
  })
_sym_db.RegisterMessage(PhotoOnDemandDevice)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
