# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/common/hub/device/common/battery_charged_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2/common/hub/device/common/battery_charged_state.proto',
  package='systems.ajax.api.desktop.v2.common.hub.device.common',
  syntax='proto3',
  serialized_options=b'\n4systems.ajax.api.desktop.v2.common.hub.device.commonP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7v2/common/hub/device/common/battery_charged_state.proto\x12\x34systems.ajax.api.desktop.v2.common.hub.device.common*\x8b\x01\n\x13\x42\x61tteryChargedState\x12%\n!BATTERY_CHARGED_STATE_UNSPECIFIED\x10\x00\x12%\n!BATTERY_CHARGED_STATE_LOW_CHARGED\x10\x01\x12&\n\"BATTERY_CHARGED_STATE_FULL_CHARGED\x10\x02\x42\x38\n4systems.ajax.api.desktop.v2.common.hub.device.commonP\x01\x62\x06proto3'
)

_BATTERYCHARGEDSTATE = _descriptor.EnumDescriptor(
  name='BatteryChargedState',
  full_name='systems.ajax.api.desktop.v2.common.hub.device.common.BatteryChargedState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BATTERY_CHARGED_STATE_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BATTERY_CHARGED_STATE_LOW_CHARGED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BATTERY_CHARGED_STATE_FULL_CHARGED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=114,
  serialized_end=253,
)
_sym_db.RegisterEnumDescriptor(_BATTERYCHARGEDSTATE)

BatteryChargedState = enum_type_wrapper.EnumTypeWrapper(_BATTERYCHARGEDSTATE)
BATTERY_CHARGED_STATE_UNSPECIFIED = 0
BATTERY_CHARGED_STATE_LOW_CHARGED = 1
BATTERY_CHARGED_STATE_FULL_CHARGED = 2


DESCRIPTOR.enum_types_by_name['BatteryChargedState'] = _BATTERYCHARGEDSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
