# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2/common/video/videoedge/mediadevice/discovering/discovery_address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common.video.videoedge.mediadevice import media_device_pb2 as v2_dot_common_dot_video_dot_videoedge_dot_mediadevice_dot_media__device__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2/common/video/videoedge/mediadevice/discovering/discovery_address.proto',
  package='systems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.discovering',
  syntax='proto3',
  serialized_options=b'P\001\272\002\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nIv2/common/video/videoedge/mediadevice/discovering/discovery_address.proto\x12Jsystems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.discovering\x1a\x38v2/common/video/videoedge/mediadevice/media_device.proto\"\x95\x01\n\x10\x44iscoveryAddress\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x65\n\x08protocol\x18\x03 \x01(\x0e\x32S.systems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.MediaDeviceProtocolB\x05P\x01\xba\x02\x00\x62\x06proto3'
  ,
  dependencies=[v2_dot_common_dot_video_dot_videoedge_dot_mediadevice_dot_media__device__pb2.DESCRIPTOR,])




_DISCOVERYADDRESS = _descriptor.Descriptor(
  name='DiscoveryAddress',
  full_name='systems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.discovering.DiscoveryAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.discovering.DiscoveryAddress.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.discovering.DiscoveryAddress.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='systems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.discovering.DiscoveryAddress.protocol', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=361,
)

_DISCOVERYADDRESS.fields_by_name['protocol'].enum_type = v2_dot_common_dot_video_dot_videoedge_dot_mediadevice_dot_media__device__pb2._MEDIADEVICEPROTOCOL
DESCRIPTOR.message_types_by_name['DiscoveryAddress'] = _DISCOVERYADDRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiscoveryAddress = _reflection.GeneratedProtocolMessageType('DiscoveryAddress', (_message.Message,), {
  'DESCRIPTOR' : _DISCOVERYADDRESS,
  '__module__' : 'v2.common.video.videoedge.mediadevice.discovering.discovery_address_pb2'
  # @@protoc_insertion_point(class_scope:systems.ajax.api.desktop.v2.common.video.videoedge.mediadevice.discovering.DiscoveryAddress)
  })
_sym_db.RegisterMessage(DiscoveryAddress)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
